apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv
  namespace: default
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: "/mnt/sonarr-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-pvc
  namespace: default
spec:
  storageClassName: microk8s-hostpath
  volumeName: sonarr-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi