apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: default
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:39.207.2
              args:
                - geftactics/home-lab
              env:
                - name: LOG_LEVEL
                  value: info
              envFrom:
                - secretRef:
                    name: renovate-env
          restartPolicy: Never