apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-shared-pv
  namespace: default
  labels:
    type: local
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: "/mnt/media-shared-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-shared-pvc
  namespace: default
spec:
  storageClassName: microk8s-hostpath
  volumeName: media-shared-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi