apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:10.10.6
        ports:
          - containerPort: 8096
            name: http-tcp
            protocol: TCP
          - containerPort: 8920
            name: https-tcp
            protocol: TCP
          - containerPort: 1900
            name: dlna-udp
            protocol: UDP
          - containerPort: 7359
            name: discovery-udp
            protocol: UDP  
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/London"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: media
            mountPath: /media
          - name: dri
            mountPath: /dev/dri
        securityContext:
          privileged: true 
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-shared-pvc
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory