theme: auto
server:
  host: 0.0.0.0
  port: 9091
log:
  level: info
authentication_backend:
  password_reset:
    disable: true
  file:
    path: /config/users.yml
    search:
      case_insensitive: true
access_control:
  default_policy: 'one_factor'
  rules:
    - domain:
      - prowlarr.k8s.squiggle.org
      - radarr.k8s.squiggle.org
      - sonarr.k8s.squiggle.org
      resources:
        - '^/api([/?].*)?$'
      policy: bypass
session:
  cookies:
    - domain: "k8s.squiggle.org"
      authelia_url: "https://auth.k8s.squiggle.org"
      expiration: 18h
      name: k8s_squiggle_org_session
      same_site: lax
storage:
  encryption_key: insecurekeyfixthislater
  local:
    path: "/db.sqlite3"
notifier:
  filesystem:
    filename: "/tmp/notification.txt"
