apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: default
data:
  users.yml: |
    users:
      geoff:
        displayname: "Geoff"
        password: "$argon2id$v=19$m=65536,t=3,p=4$hauzs6SlcEt3B5ubkXYxHg$7s7q9fJc7BRggvmcTJAnV8U7ZjDiFgswuOEVBqfihMs"
        email: geoff@host
        groups:
          - users
          - admins
  configuration.yml: |
    theme: auto
    server:
      host: 0.0.0.0
      port: 9091
    log:
      level: info
    authentication_backend:
      password_reset:
        disable: true
      file:
        path: /config/users.yml
        search:
          case_insensitive: true
    access_control:
      default_policy: 'one_factor'
    session:
      cookies:
        - domain: "k8s.squiggle.org"
          authelia_url: "https://auth.k8s.squiggle.org"
          expiration: 18h
          name: k8s_squiggle_org_session
          same_site: lax
    storage:
      encryption_key: insecurekeyfixthislater
      local:
        path: "/db.sqlite3"
    notifier:
      filesystem:
        filename: "/tmp/notification.txt"
