apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - sealed-secret.yaml
  - service.yaml

configMapGenerator:
  - name: authelia-config
    namespace: default
    files:
      - configmap.yml
    options:
      annotations:
        "config.kubernetes.io/depends-on": "ConfigMap/authelia-config"
