apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:5.18.4
        ports:
          - containerPort: 7878
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Europe/London"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: media
            mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-shared-pvc