apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: sealed-secrets
      version: "2.5.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    fullnameOverride: sealed-secrets-controller
