apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "lets-encrypt"
spec:
  tls:
    - hosts:
      - it-tools.k8s.squiggle.org
      secretName: it-tools-tls-secret
  rules:
  - host: it-tools.k8s.squiggle.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: it-tools
            port:
              number: 80
