apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hostmaster@squiggle.org
    privateKeySecretRef:
      name: lets-encrypt-priviate-key
    solvers:
    - http01:
        ingress:
          class: public
